### ISSUE TITLE
fzf hint color is covered

### ISSUE THREAD

**Issue by wy15** [connorholyday/kitty-snazzy#1]
fzf hint color is covered

**Comment by connorholyday** [comment]
Could you provide a screenshot and the commands to reproduce?

**Comment by wy15** [comment]
![screen shot 2018-10-08 at 08 51 33](https://user-images.githubusercontent.com/1898296/46589003-72f15c80-cad7-11e8-83fc-9cca1f19fbf7.png)

**Comment by wy15** [comment]
It should like this.
![screen shot 2018-10-08 at 08 52 57](https://user-images.githubusercontent.com/1898296/46589016-99af9300-cad7-11e8-9507-09e7453dcd87.png)

**Comment by wy15** [comment]
I'm so sorry.Not 'fzf',it's 'zsh-autosuggestions'.I solved this by changing 'AUTOSUGGESTION_HIGHLIGHT_COLOR'.

Thank you for your help and your color scheme.

**Comment by connorholyday** [comment]
If this is something you think should be part of the colorscheme then feel free to make a Pull Request 👍
