### ISSUE TITLE
No cursor color or cursor_text_color

### ISSUE THREAD

**Issue by Luflosi** [connorholyday/kitty-snazzy#5]
This theme provides no `cursor` color or `cursor_text_color`. Is that intended? The screenshot shows a pink cursor color.

**Comment by connorholyday** [comment]
This is a good catch, thanks bringing it up. Would you like to make a PR to fix this? If not then I'll get around to it when my evenings clear up

**Comment by Luflosi** [comment]
Sure, I can make a PR.
